/* NOTE this file is autogenerated by Scalate : see http://scalate.fusesource.org/ */
package layout

import _root_.scala.collection.JavaConversions._
import _root_.org.fusesource.scalate.support.TemplateConversions._
import _root_.org.fusesource.scalate.util.Measurements._

object $_scalate_$deletePage_jade {
  def $_scalate_$render($_scalate_$_context: _root_.org.fusesource.scalate.RenderContext): Unit = {
    import _root_.org.fusesource.scalate.support.RenderHelper.{sanitize=>$_scalate_$_sanitize, preserve=>$_scalate_$_preserve, indent=>$_scalate_$_indent, smart_sanitize=>$_scalate_$_smart_sanitize, attributes=>$_scalate_$_attributes}
    ;{
      val context: _root_.org.fusesource.scalate.RenderContext = $_scalate_$_context.attribute("context")
      import context._
      
      
      $_scalate_$_context << ( "<html></html>\n<head></head>\n<title>my jade template</title>\n<script type=\"text/javascript\" src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js\"></script>\n<script type=\"text/javascript\" src=\"/assets/delete.js\"></script>\n<body></body>\n<p>Enter data to delete</p>\n<form method=\"post\" id=\"deleteForm\">\n  <select name=\"dropdown\">\n    <option value=\"\" disabled=\"disabled\" selected=\"selected\">Select one</option>\n    <option value=\"id\">By EmpID</option>\n    <option value=\"name\">By Name</option>\n    <option value=\"salary\">By Salary</option>\n  </select>\n  <input type=\"text\" name=\"input\"/>\n  <input type=\"button\" value=\"Delete\" id=\"deleteButton\"/>\n  <br/>\n  <div id=\"del_div\"></div>\n</form>\n" );
    }
  }
}


class $_scalate_$deletePage_jade extends _root_.org.fusesource.scalate.Template {
  def render(context: _root_.org.fusesource.scalate.RenderContext): Unit = $_scalate_$deletePage_jade.$_scalate_$render(context)
}
