/* NOTE this file is autogenerated by Scalate : see http://scalate.fusesource.org/ */
package layout

import _root_.scala.collection.JavaConversions._
import _root_.org.fusesource.scalate.support.TemplateConversions._
import _root_.org.fusesource.scalate.util.Measurements._

object $_scalate_$input_jade {
  def $_scalate_$render($_scalate_$_context: _root_.org.fusesource.scalate.RenderContext): Unit = {
    import _root_.org.fusesource.scalate.support.RenderHelper.{sanitize=>$_scalate_$_sanitize, preserve=>$_scalate_$_preserve, indent=>$_scalate_$_indent, smart_sanitize=>$_scalate_$_smart_sanitize, attributes=>$_scalate_$_attributes}
    ;{
      val context: _root_.org.fusesource.scalate.RenderContext = $_scalate_$_context.attribute("context")
      import context._
      
      
      ;{
        val address: String = $_scalate_$_context.attribute("address")
        $_scalate_$_context << ( "<html lang=\"en\"></html>\n<head></head>\n<script type=\"text/javascript\"></script>\n<body></body>\n<h1>Employee Information</h1>\nEmp Id :\n<br/>\n<input type=\"text\" name=\"empID\"/>\n<br/>\nName:\n<br/>\n<input type=\"text\" name=\"name\"/>\n<br/>\nSalary :\n<br/>\n<input type=\"text\" name=\"salary\"/>\n<br/>\nAddress :\n<br/>\n<input type=\"text\" name=\"address\"/>\n<br/>\n<input type=\"submit\" value=\"Add\"/>\n" );
      }
    }
  }
}


class $_scalate_$input_jade extends _root_.org.fusesource.scalate.Template {
  def render(context: _root_.org.fusesource.scalate.RenderContext): Unit = $_scalate_$input_jade.$_scalate_$render(context)
}
