/* NOTE this file is autogenerated by Scalate : see http://scalate.fusesource.org/ */
package layout

import _root_.scala.collection.JavaConversions._
import _root_.org.fusesource.scalate.support.TemplateConversions._
import _root_.org.fusesource.scalate.util.Measurements._

object $_scalate_$welcome_jade {
  def $_scalate_$render($_scalate_$_context: _root_.org.fusesource.scalate.RenderContext): Unit = {
    import _root_.org.fusesource.scalate.support.RenderHelper.{sanitize=>$_scalate_$_sanitize, preserve=>$_scalate_$_preserve, indent=>$_scalate_$_indent, smart_sanitize=>$_scalate_$_smart_sanitize, attributes=>$_scalate_$_attributes}
    ;{
      val context: _root_.org.fusesource.scalate.RenderContext = $_scalate_$_context.attribute("context")
      import context._
      
      
      $_scalate_$_context << ( "<html></html>\n<head></head>\n<title>my jade template</title>\n<script type=\"text/javascript\" src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js\"></script>\n<script type=\"text/javascript\" src=\"/assets/add.js\"></script>\n<body></body>\n<h1>Enter your information</h1>\n<form method=\"post\" id=\"addForm\">\n  Emp Id :\n  <br/>\n  <input type=\"text\" name=\"id\"/>\n  <br/>\n  Name:\n  <br/>\n  <input type=\"text\" name=\"name\"/>\n  <br/>\n  Salary :\n  <br/>\n  <input type=\"text\" name=\"salary\"/>\n  <br/>\n  <input type=\"button\" value=\"Add\" id=\"addButton\"/>\n</form>\n" );
    }
  }
}


class $_scalate_$welcome_jade extends _root_.org.fusesource.scalate.Template {
  def render(context: _root_.org.fusesource.scalate.RenderContext): Unit = $_scalate_$welcome_jade.$_scalate_$render(context)
}
